### ISSUE TITLE
GML and gmd Object factory cleanup

### ISSUE THREAD

**Issue by ibazar83** [fmidev/fmi-avi-xmlmodel#1]
Hi,
please, in fmi-avi-xmlmodel/fmi-avi-xmlmodel-aixm511-wx/pom.xml add the cleanup section for the removal of GML and gmd ObjectFactory.java classes, as already done in other pom files. Or is there any reason for which they have not been removed in this specific pom?
Thanks

**Comment by ilkkarinne** [comment]
Hi @ibazar83: thanks for reporting this, It will be fixed in the next release
